sudo: required
services:
- docker
before_install:
- docker build -t yoyowu1000/docker-react-course -f Dockerfile.dev .
script:
- docker run -e CI=true yoyowu1000/docker-react-course npm run test -- --coverage
language: generic
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: CAc0bqZX8Oawof+lmfuTMK2VnLSEtT8jmSufr935C2X9BMLKmXxIvJs3viHbBRSk3prSH2W69tFst2cb+N6UATNy5SjfRdW8MxgxTtq2Ynem7e6r52uF3R6ks81/QN6uHFkCiLJUhrTr0GcY9BbReoUCIwkZBzS5bI6a+/Fm38KssuLyCfER1iFxqiMCQ3cvI3WPfTLpqWbNwnI3wIqgWoFK7LLPcmDAUeRVSZUB3Oq6/3QnquYqOLFTK5wb1o+wITJek8nDXbGcf+qcJ+pZyLd/W4AsLRWuhmgv5KouLzJm10fYerjBa+p8wjYrhJOvlheJVNPzpYbYX07WoE570RR55J6lUZqedyo7ngSPBe5cMZH8v7OPNFwGLW3k3Iy5P2wyGHydUSnDpEQNfROHAThAkA8C7qaLwk3OQxD31nMKSWaV6DC1D9lG65t3HbiCGAjVaT29EDmymtZuC7QCtwvIdSBxZHtCvPgV2noF/nNu02QOzUYmMde3AJq0dn8yYCgO/uwFw7OaV16fPdzwvLeNnnm3idLFGmOFjJwv77uv2R1DHYBnrXyLoQAV4CnELWNXD/NCavcf0dAcmkJq1t2+4/okD+jogNzUD2lpdXAshwsCzeMDjPEgRrPNCckbgAiEkqS8/BPFTjWSngPkCeBJVmUaHhrlZjOlC7ZbTnQ=
  secret_access_key:
    secure: OY7d9Qiu8LAsgW9VdpXe0yBsKB2HfyOe7hVDbG6+uHDOviXTGrsnYfNNf2X+x6LR7Iu0dJ+b0NjGy5zFtevJiN30CHwKJd9H58iJgo3PaO46eRB2BPHIdPbF7D9BYKVqj5B0uCQMlGOXTGc+/dQiwk27VVV2SO35BUQaJgaGRr9Gk7eWeaTecWKG0WEr5olLHX7w+AFe2px+9s5e8pq0mfTD2fHz3/BAkwpqle0DoVhlq78Qt16sP6emtShrGBFHi8yBmYenugVWEjFyyLBxtZse2AoJsKEHrHk/pJeP4inULFFgvSY9Eu9srVOVmG2VY9tqffKpiljExKF9DFMy9i30RPirm/sPqdUCTZ2ynKsrR+lB8Ep5qnJVqfqAWnVDwc4Jf1gmi6jc4OcLGGK7j8xJkfu9bEEqhw3gmLoMYrj5Mgr4UsSdhQ+fLplbCAJA1X7W0n69DBwjpBTsEd5YWLhjAxz2DF/r+30PO7jy8AQ4p5WT50O9txqbMLpvURbOfqQlzW1kPzmszYDWHIV6EDMkzJOQvb1JpZhj1usdhG2iMuINU+nsG5dJFhFTaCbZG4tmVI9v4b7adr4A0GQ/Qmwjd7EV5w4ukzbADrRvAyUimRKuuhMyz/gf/agguHKtk2XutTiYvg1WWd3YA+H1yle4vJ5euoaHBAwyFIhqKig=
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-871201622408
  bucket_path: docker-react
  on:
    branch: master

