sudo: required
services:
- docker
before_install:
- docker build -t yoyowu1000/docker-react-course -f Dockerfile.dev .
script:
- docker run -e CI=true yoyowu1000/docker-react-course npm run test -- --coverage
language: generic
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: dYXFgn2c/GsF/yF0Z1vz4PV0mIv9jNG6GdsZ/GGUHAnyPV99ZSpZEcb+az9eb1Ji71xfxIUIy5rfqDM8lb93hl0j2HnLDfwW3RkD71mbbgpSZx/NQhkiVpxEn3aHYTwfu3Jop5Q853HXYmcObixMnjbOKZ6Fy5fQEtNbX2e+X41xjIsxUHbb8EFHCD8oEm0YFkozzFLF5zdYV77QXJauTOOoa9eTI0RmRpdUH34FSdCCkeoX0sL63POEzfUQHJcmAn9kJejfb5l34UPuWZ5FMMzwcnUQB7DWKBwnPriQKG58slPTdTa5Mqp7NxE+y3r91ZNW0jchkDJTTRaZhU2N1OJ51BaCpi0CTcKMfdoOD8kiwA1hKu2HkQE9SUX+3XzydPIxre8mzxiEEowFvSt9kpHazd8bGym+oSzHGz5i5Z0YBRZed2SOgZhOg3NQQkoP44WIww0E5uCy6STn9idMNIZwKmf34FfvKR+KyxuldQKQ+KlnpaSdE5JhoHhAP7syhgyCDBDDEt6cHXMOb0ImZplpi7IowV1xX6YBw1D6lpAIV/WLCliiCKWMLBxEazN/cit9DcGHLCqoluSzjTdSHFmjmk8PqIw96U5HBxvN7N8nKrV7qXov4I10BdnbNtBb9ZzUtZnK60IZUswdJT+H+wbY1gsfZ5ciVdPo+dISwUE=
  secret_access_key:
    secure: X+kqXY6Y/5k8gybTHZGWPJ9+00mJJtlnvCENV/QkuitVKEAAZp3QTwrMIoSfJe9ibfYOEHJibLbZB0ZNEioMRSsqqVWfZv3FFmHkjhDXJInGtEWp2sdLsrGNuIEU2PLWj3YDv/E/OHlVYOvcD8ry1+tf2vNER1XkWnmKrxGkQIVs4HzHsM1fX5YtQFWLEAPWCt78/qPkke3UeRgoT7p58oK3ixpwzH4893E7kkcCKPEldnhCE4heJqc/JacOsS0QMaBXd/vQSXef3njkK/a81hY2f/LbKJaH2+OHUkbI68hENM3pO6DB/9+BF+ZL0YNiI83elTE7Q8zT5oKtzYvFX8JGmxaLTkWowVDRD824snK6nilDnd6jKqhXVqKLnX2kYmm2pDACXgzshFeK8D9D5GOWBSmh2gbsIilrXzg6b71TqJjYhXCPgixzrJLVqq19wzvOYIxiz/9jD+nYI1eZD4xFuzyMDh96hkPjs+Stq1hfIV+609xECqe/yPVHk/4F75/ftN8Ph0t+1iLoHINPpA8Jz+AoQEbKg6DTYilV6KYWHELMHK8WZZYYkNBcguBuvrkgRYIPW1WZLvI3qHEIC+tXF/9vfLbwCkmCjTcVZsFmb3iFCsowDl4nL+YgGgM6dKFowI6A09AVtm/QaHJBOrD+f4xv+yu6Hc/l1YNXvt8=
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-871201622408
  bucket_path: docker-react
  on:
    branch: master