FROM node:alpine

WORKDIR '/app'

COPY --chown=node:node package.json .
RUN npm install
RUN npm config set unsafe-perm true
#RUN npm install -g --unsafe-perm=true --allow-root
#RUN chmod a+w node_modules -R
COPY --chown=node:node . . 

CMD ["npm", "run", "start"] 